require "prop_logic/version"
require "prop_logic/term"
require 'prop_logic/functions'
require "prop_logic/and_term"
require "prop_logic/or_term"
require "prop_logic/not_term"
require "prop_logic/then_term"
require 'prop_logic/variable'
require 'prop_logic/constants'
require 'prop_logic/brute_force_sat_solver'
require 'prop_logic/sat_solver'
